# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1puz19DXNedX_l5_OcRESf4xBJ8A6IIp9
"""

from matplotlib import pyplot as plt
import cv2

image = cv2.imread("Romina BTS.jpg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.imshow(image)

model = cv2.CascadeClassifier("model.xml")

Kimteahung_face = model.detectMultiScale(image)

print(Kimteahung_face)

image.shape

image = cv2.rectangle(image, (100,100), (200,200), (0,0,255), 3)

x = Kimteahung_face[0][0]
y = Kimteahung_face[0][1]
a = Kimteahung_face[0][2]
b = Kimteahung_face[0][3]

image = cv2.rectangle(image, (x,y), (x+a,y+b), (0,0,255), 3)

image = cv2.imread("Romina BTS.jpg")
model = cv2.CascadeClassifier("model.xml")
face = model.detectMultiScale(image)
x = Kimteahung_face[0][0]
y = Kimteahung_face[0][1]
a = Kimteahung_face[0][2]
b = Kimteahung_face[0][3]
image = cv2.rectangle(image, (x,y), (x+a,y+b), (0,255,0), 3)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
plt.imshow(image)